//cart
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
//restock
export const UPDATE_RESTOCK_ITEM = "UPDATE_RESTOCK_ITEM";
export const ADD_RESTOCK_ITEM = "ADD_RESTOCK_ITEM";
export const DELETE_RESTOCK_ITEM = "DELETE_RESTOCK_ITEM";
//inventory
export const UPDATE_SEARCH_TEXT = "UPDATE_SEARCH_TEXT";
export const SET_INVENTORY = "SET_INVENTORY";
export const UPDATE_INVENTORY_ITEM = "UPDATE_INVENTORY_ITEM";
//user
export const SET_SHOPS = "SET_SHOPS";
export const SET_CURRENT_SHOP = "SET_CURRENT_SHOP";